config/routes.rb
Microarray2::Application.routes.draw do
  resources :experiments
  resources :probes do
		get 'thumbnail', on: :member
		get 'image', 		 on: :member
	end
	resources :templates do
	  get 'thumbnail', on: :member
	end
  resources :testspots
	resources :template_control_points

  root :to => 'experiments#index'

end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  attr_accessor :zip_file
  belongs_to :template
  has_many   :probes

	before_create do
		self.system_input_folder  = "../input/" 
    self.system_output_folder = "../output/"
		self.probe_folder_name = ""
		self.probe_image_wildcard = "*.tif"
	end
	
	after_create do
		self.probe_folder_name = "../input/#{self.id}"
    self.save
	end
	
  def name
  	"#{self.id}, #{self.comments}"
  end
end

app/models/extractor.rb
require 'zip/zip'

class Extractor
  def self.unzip_file(file, destination)
    Zip::ZipFile.open(file) { |zip_file|
      zip_file.each { |f|
        f_path=File.join(destination, f.name)
        FileUtils.mkdir_p(File.dirname(f_path))
        zip_file.extract(f, f_path) unless File.exist?(f_path)
      }
    }
  end
end

app/models/probe.rb
class Probe < ActiveRecord::Base
  set_primary_key :id
  belongs_to :experiment
  has_many   :testspots

  def thumbnail_filename
    filename_witout_extension = File.basename(self.filename).sub(".tif", "")
    "#{filename_witout_extension}_thumbnail.png"
  end

  def only_filename
    File.basename self.filename
  end
end

app/models/template.rb
class Template < ActiveRecord::Base
  has_many :experiments

	def template_control_points
		TemplateControlPoint.where(template_id: self.id)
	end
end

app/models/template_control_point.rb
class TemplateControlPoint < ActiveRecord::Base

end

app/models/testspot.rb
class Testspot < ActiveRecord::Base
  belongs_to :probe
end

app/models/zip.rb
require 'zip/zip'
class Zip
  def self.unzip_file(file, destination)
    Zip::ZipFile.open(file) { |zip_file|
      zip_file.each { |f|
        f_path=File.join(destination, f.name)
        FileUtils.mkdir_p(File.dirname(f_path))
        zip_file.extract(f, f_path) unless File.exist?(f_path)
      }
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController 
  
  def index
    @experiments = Experiment.all
  end

  def show
    @experiment = Experiment.find(params[:id])
    # format.json { render json: @article.as_json(only: [:id, :name, :content], include: [:author, {comments: {only:[:id, :name, :content]}}]) }

		gon.template = @experiment.template.as_json(methods: [:template_control_points])
		gon.probes = @experiment.probes
  end

  def new
    @templates = Template.all
    @experiment = Experiment.new
  end

  def edit
    @experiment = Experiment.find(params[:id])
  end

  def create
    @experiment = Experiment.new(params[:experiment])    
		File.open(Rails.root.join("tmp", params[:experiment][:zip_file].original_filename),'wb') { |f| f.write params[:experiment][:zip_file].read }
    if @experiment.save
			Extractor.unzip_file(Rails.root.join("tmp", params[:experiment][:zip_file].original_filename),
	                         File.join(File.expand_path(ENV["MICROARRAY_ANALYZER_PATH"]), "input", "#{@experiment.id}"))    
			
      redirect_to @experiment, notice: 'Experiment was successfully created.'
    else
      render action: "new" 
    end
  end

  def update
    @experiment = Experiment.find(params[:id])
    respond_to do |format|
      if @experiment.update_attributes(params[:experiment])
        format.html { redirect_to @experiment, notice: 'Experiment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @experiment = Experiment.find(params[:id])
    @experiment.destroy
    respond_to do |format|
      format.html { redirect_to experiments_url }
      format.json { head :no_content }
    end
  end

   def unzip_file(file, destination)
    Zip::ZipFile.open(file) { |zip_file|
      zip_file.each { |f|
        f_path=File.join(destination, f.name)
        FileUtils.mkdir_p(File.dirname(f_path))
        zip_file.extract(f, f_path) unless File.exist?(f_path)
      }
    }
  end
  
end

app/controllers/probes_controller.rb
class ProbesController < ApplicationController
  respond_to :html, :json
  def show
    @probe = Probe.find(params[:id])
    gon.probe = @probe
    respond_with(@probe)
  end

	def thumbnail
		probe = Probe.find(params[:id])
		send_data open(ENV["MICROARRAY_ANALYZER_PATH"] + "input/#{probe.experiment.id}/#{File.basename(probe.filename)}.thumbnail.png", "rb") { |f| f.read }
	end
	
	def image
		probe = Probe.find(params[:id])
		send_data open(ENV["MICROARRAY_ANALYZER_PATH"] + "input/#{probe.experiment.id}/#{File.basename(probe.filename)}.png", "rb") { |f| f.read },
							:type => "image/png"
	end
end

app/controllers/template_control_points_controller.rb
class TemplateControlPointsController < ApplicationController
	respond_to :html, :json
	def create
		template_control_point = TemplateControlPoint.new(template_id: params[:template_id], x: params[:y], y: params[:y])
		template_control_point.save
		respond_with(template_control_point)
	end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
	def thumbnail
		experiment = Experiment.find(params[:id])
		send_data open(ENV["MICROARRAY_ANALYZER_PATH"] + 
									"input/templates/#{experiment.id}/#{File.basename(experiment.template.image_filename)}.thumbnail.png", "rb") { |f| f.read }		
	end
end

app/controllers/testspots_controller.rb
class TestspotsController < ApplicationController
  respond_to :html, :json

  def show
    @testspot = Testspot.find(params[:id])
    respond_with(@testspot)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def initialize_javascripts
    controller_name = controller.controller_name.classify
    javascript_tag <<-SCRIPT
      $(document).ready(function() {
        if(typeof #{controller_name} !== 'undefined'){
         #{controller_name}.init();
        }
      });
    SCRIPT
  end

end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/probes_helper.rb
module ProbesHelper
end

app/helpers/testspots_helper.rb
module TestspotsHelper
end

app/views/experiments/_form.html.erb
<div class"row">
  <%= form_for(@experiment, html: { class: "form-horizontal"}) do |f| %>
    <fieldset>
      <div class="control-group">
        <%= f.label :comment, 'Comments', class: "control-label" %>
        <div class="controls">
          <%= f.text_area :comments, class: "input-xlarge", rows: 4 %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :template_id, 'Template', class: "control-label" %>
        <div class="controls">
          <%= f.select :template_id, @templates.collect {|t| [t.image_filename, t.id]}, {include_bank: true} %>
        </div>
      </div>
      <div class='control-group'>
        <%= f.label :zip_file, 'Probe Images', class: "control-label" %>
        <div class="controls">
          <%= f.file_field :zip_file, class: "input-file" %>
        </div>
      </div>
    </fieldset>
    <div class="form-actions">
      <%= f.submit 'Save', class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/experiments/edit.html.erb
<h1>Editing experiment</h1>

<%= render 'form' %>

<%= link_to 'Show', @experiment %> |
<%= link_to 'Back', experiments_path %>

app/views/experiments/index.html.erb
<div class="row">
  <div class="span4 offset4">
    <h3>Choose an experiment</h3>
    <%= form_tag("/experiments", class: "well form-search") do %>
      <%= select_tag("experiments", options_from_collection_for_select(@experiments, "id", "name"), include_blank: true, prompt: "Choose an experiment") %>
    <% end -%>
    <%= link_to 'New Experiment', new_experiment_path, class: "btn" %>
  </div>
</div>

app/views/experiments/new.html.erb
<h2>New experiment</h2>

<%= render 'form' %>

app/views/experiments/show.html.erb
<div class="row">
  <h2>Template Image</h2>
  <ul class="thumbnails">
    <li class="span3">
      <a href="#template_modal" data-toggle="modal" class="thumbnail">
        <%= image_tag(thumbnail_template_path(@experiment)) %>
      </a>
    </li>
  </ul>
  <% if TemplateControlPoint.find_all_by_template_id(@experiment.template.id).count == 3 %>
    <%= hidden_field_tag 'template_control_points', 'yes' %>
  <% else %>
    <%= hidden_field_tag 'template_control_points', 'no' %>
  <% end %>
</div>


<div class="row">
  <h2>Probe Images</h2>
  <ul class="thumbnails">
    <% @experiment.probes.each do |probe| %>
      <li class="span3">                
        <% if probe.evaluated %>
          <%= link_to image_tag(thumbnail_probe_path(probe)), probe_path(probe), class: "thumbnail" %>        
          <span class="label label-success">Evaluated</span>
        <% else %>
          <a href="#probe_<%= probe.id %>_modal" data-toggle="modal" class="thumbnail probe_thumbnail">
            <%= image_tag(thumbnail_probe_path(probe)) %>
          </a>
          <span class="label label-important">Not evaluated</span>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>


<div class="modal hide" id="template_modal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Template Image</h3>
  </div>
  <div class="modal-body">
    <p>Click 3 points on the image to form a polygon (the oder of click in important)</p>
    <div id="template_image"></div>
  </div>
  <div class="modal-footer">
    <a href="/template_control_points/<%= @experiment.template.id %>" class="btn" data-dismiss="modal">Clear Control Points</a>
  </div>
</div>

<% @experiment.probes.where(evaluated: false).each do |probe| %>
  <div class="modal hide probe_modal" id="probe_<%= probe.id%>_modal">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">×</button>
      <h3>Probe Image #<%= probe.id%></h3>
    </div>
    <div class="modal-body">
      <p>Click 3 points on the image to form a polygon (the oder of click in important)</p>
      <div id="probe_<%= probe.id %>_image"></div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Microarray2" %></title>
    <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Microarray2</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <%= yield %>
      </div>
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= include_gon(:camel_case => true) %>
    <%= initialize_javascripts %>
  </body>
</html>

app/views/probes/show.html.erb
<div class="row">
  <div class="span8">
    <div id="<%= @probe.only_filename.split('.').first %>"></div>
  </div>
  <div class="span3">
    <table class="table">
      <thead>
        <tr>
          <th>Key</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        <% ['rect_x', 'rect_y', 'mean', 'std_dev', 'max', 'min', 'median'].each do |n| %>
          <tr id="<%=n%>">
            <td><%= n.humanize %></td>
            <td></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="span7">
    <table id="<%= 'probe' + @probe.id.to_s %>" class="table">
      <thead>
        <th>#</th>
        <th>Rect x</th>
        <th>Rect y</th>
        <th>Rect width</th>
        <th>Rect height</th>
        <th>Mean</th>
        <th>Std. Dev.</th>
        <th>Max</th>
        <th>Min</th>
        <th>Median</th>
      </thead>
      <tbody>
        <% @probe.testspots.each_with_index do |testspot, index| %>
          <tr id="<%= 'testspot_' + testspot.id.to_s %>">
            <td><%= index = index + 1 %></td>
            <td><%= testspot.rect_x%></td>
            <td><%= testspot.rect_y%></td>
            <td><%= testspot.rect_width%></td>
            <td><%= testspot.rect_height%></td>
            <td><%= testspot.mean %></td>
            <td><%= testspot.std_dev %></td>
            <td><%= testspot.max %></td>
            <td><%= testspot.min %></td>
            <td><%= testspot.median %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>